'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'zh' | 'vi';

export interface Translations {
  [key: string]: string | Translations;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string>) => string;
  availableLanguages: { code: Language; name: string; nativeName: string }[];
}

const availableLanguages: { code: Language; name: string; nativeName: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
];

// English translations (default)
const en: Translations = {
  common: {
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    next: 'Next',
    previous: 'Previous',
    back: 'Back',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    required: 'Required',
    optional: 'Optional',
    search: 'Search',
    filter: 'Filter',
    all: 'All',
    yes: 'Yes',
    no: 'No',
    edit: 'Edit',
    delete: 'Delete',
    archive: 'Archive',
    view: 'View',
    create: 'Create',
    add: 'Add',
    remove: 'Remove',
    close: 'Close',
    confirm: 'Confirm',
    refresh: 'Refresh',
    logout: 'Sign Out',
    login: 'Sign In',
  },
  auth: {
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    welcomeBack: 'Welcome back',
    enterCredentials: 'Enter your email and password to access your account',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    clientPortal: 'Client Self-Registration',
    staffLogin: 'Staff Login',
  },
  dashboard: {
    title: 'Dashboard',
    welcome: 'Welcome',
    totalClients: 'Total Clients',
    activeClients: 'Active Clients',
    pendingTasks: 'Pending Tasks',
    openTasks: 'Open Tasks',
    upcomingDeadlines: 'Upcoming Deadlines',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    newIntake: 'New Intake',
    viewClients: 'View Clients',
    viewTasks: 'View Tasks',
    viewCalendar: 'View Calendar',
  },
  clients: {
    title: 'Clients',
    newClient: 'New Client',
    clientDetails: 'Client Details',
    firstName: 'First Name',
    lastName: 'Last Name',
    preferredName: 'Preferred Name',
    dateOfBirth: 'Date of Birth',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    streetAddress: 'Street Address',
    city: 'City',
    state: 'State',
    zipCode: 'ZIP Code',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    pending: 'Pending',
    archived: 'Archived',
    copyPhone: 'Copy phone number',
    copyEmail: 'Copy email address',
    copied: 'Copied!',
  },
  intake: {
    title: 'Client Intake',
    step1: 'Participant Details',
    step2: 'Emergency Contact',
    step3: 'Case Management',
    step4: 'Demographics',
    step5: 'Household',
    personalInfo: 'Personal Information',
    contactInfo: 'Contact Information',
    addressInfo: 'Address Information',
    emergencyContact: 'Emergency Contact',
    caseInfo: 'Case Information',
    demographics: 'Demographics',
    household: 'Household Members',
  },
  tasks: {
    title: 'Tasks',
    newTask: 'New Task',
    taskTitle: 'Task Title',
    description: 'Description',
    dueDate: 'Due Date',
    priority: 'Priority',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    status: 'Status',
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    assignedTo: 'Assigned To',
    claimTask: 'Claim Task',
    openToClaim: 'Open to Claim',
    unassigned: 'Unassigned',
  },
  alerts: {
    title: 'Alerts & Notifications',
    markAsRead: 'Mark as Read',
    markAllRead: 'Mark All as Read',
    archive: 'Archive',
    priority: 'Priority',
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    unread: 'Unread',
  },
  housing: {
    title: 'Housing',
    programs: 'Programs',
    applications: 'Applications',
    waitlist: 'Waitlist',
    status: 'Status',
    available: 'Available',
    unavailable: 'Unavailable',
  },
  documents: {
    title: 'Documents',
    upload: 'Upload Document',
    download: 'Download',
    verified: 'Verified',
    pendingVerification: 'Pending Verification',
    type: 'Document Type',
    uploadedAt: 'Uploaded',
  },
  calendar: {
    title: 'Calendar',
    today: 'Today',
    month: 'Month',
    week: 'Week',
    day: 'Day',
    newEvent: 'New Event',
  },
  admin: {
    title: 'Admin Panel',
    users: 'User Management',
    createUser: 'Create User',
    userRole: 'Role',
    roles: {
      admin: 'Administrator',
      caseManager: 'Case Manager',
      staff: 'Staff',
      volunteer: 'Volunteer',
      client: 'Client',
    },
    activeUsers: 'Active Users',
    deactivate: 'Deactivate',
    activate: 'Activate',
  },
  profile: {
    title: 'Profile Settings',
    personalInfo: 'Personal Information',
    changePassword: 'Change Password',
    notifications: 'Notification Settings',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
  },
  clientPortal: {
    title: 'Client Self-Registration',
    welcome: 'Welcome to ClientHub',
    description: 'Complete this form to register for services. Your information will be kept confidential.',
    step1Title: 'Create Account',
    step2Title: 'Your Address',
    step3Title: 'Service Agreement',
    step4Title: 'Sign & Submit',
    agreementText: 'I agree to the terms and conditions and authorize the collection of my information for service purposes.',
    signatureLabel: 'Please sign below',
    clearSignature: 'Clear Signature',
    submitApplication: 'Submit Application',
  },
};

// Spanish translations
const es: Translations = {
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    submit: 'Enviar',
    next: 'Siguiente',
    previous: 'Anterior',
    back: 'Atrás',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    required: 'Requerido',
    optional: 'Opcional',
    search: 'Buscar',
    filter: 'Filtrar',
    all: 'Todos',
    yes: 'Sí',
    no: 'No',
    edit: 'Editar',
    delete: 'Eliminar',
    archive: 'Archivar',
    view: 'Ver',
    create: 'Crear',
    add: 'Agregar',
    remove: 'Eliminar',
    close: 'Cerrar',
    confirm: 'Confirmar',
    refresh: 'Actualizar',
    logout: 'Cerrar sesión',
    login: 'Iniciar sesión',
  },
  auth: {
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    forgotPassword: '¿Olvidó su contraseña?',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    signOut: 'Cerrar sesión',
    welcomeBack: 'Bienvenido de nuevo',
    enterCredentials: 'Ingrese su correo y contraseña para acceder a su cuenta',
    noAccount: '¿No tiene una cuenta?',
    hasAccount: '¿Ya tiene una cuenta?',
    clientPortal: 'Auto-registro de clientes',
    staffLogin: 'Inicio de sesión del personal',
  },
  dashboard: {
    title: 'Panel de control',
    welcome: 'Bienvenido',
    totalClients: 'Total de clientes',
    activeClients: 'Clientes activos',
    pendingTasks: 'Tareas pendientes',
    openTasks: 'Tareas abiertas',
    upcomingDeadlines: 'Próximos plazos',
    recentActivity: 'Actividad reciente',
    quickActions: 'Acciones rápidas',
    newIntake: 'Nueva admisión',
    viewClients: 'Ver clientes',
    viewTasks: 'Ver tareas',
    viewCalendar: 'Ver calendario',
  },
  clients: {
    title: 'Clientes',
    newClient: 'Nuevo cliente',
    clientDetails: 'Detalles del cliente',
    firstName: 'Nombre',
    lastName: 'Apellido',
    preferredName: 'Nombre preferido',
    dateOfBirth: 'Fecha de nacimiento',
    phone: 'Teléfono',
    email: 'Correo electrónico',
    address: 'Dirección',
    streetAddress: 'Dirección',
    city: 'Ciudad',
    state: 'Estado',
    zipCode: 'Código postal',
    status: 'Estado',
    active: 'Activo',
    inactive: 'Inactivo',
    pending: 'Pendiente',
    archived: 'Archivado',
    copyPhone: 'Copiar número de teléfono',
    copyEmail: 'Copiar correo electrónico',
    copied: '¡Copiado!',
  },
  intake: {
    title: 'Admisión de cliente',
    step1: 'Datos del participante',
    step2: 'Contacto de emergencia',
    step3: 'Gestión de casos',
    step4: 'Demografía',
    step5: 'Hogar',
    personalInfo: 'Información personal',
    contactInfo: 'Información de contacto',
    addressInfo: 'Información de dirección',
    emergencyContact: 'Contacto de emergencia',
    caseInfo: 'Información del caso',
    demographics: 'Demografía',
    household: 'Miembros del hogar',
  },
  tasks: {
    title: 'Tareas',
    newTask: 'Nueva tarea',
    taskTitle: 'Título de la tarea',
    description: 'Descripción',
    dueDate: 'Fecha de vencimiento',
    priority: 'Prioridad',
    high: 'Alta',
    medium: 'Media',
    low: 'Baja',
    status: 'Estado',
    pending: 'Pendiente',
    inProgress: 'En progreso',
    completed: 'Completada',
    assignedTo: 'Asignado a',
    claimTask: 'Reclamar tarea',
    openToClaim: 'Disponible',
    unassigned: 'Sin asignar',
  },
  alerts: {
    title: 'Alertas y Notificaciones',
    markAsRead: 'Marcar como leído',
    markAllRead: 'Marcar todo como leído',
    archive: 'Archivar',
    priority: 'Prioridad',
    critical: 'Crítica',
    high: 'Alta',
    medium: 'Media',
    low: 'Baja',
    unread: 'No leído',
  },
  housing: {
    title: 'Vivienda',
    programs: 'Programas',
    applications: 'Solicitudes',
    waitlist: 'Lista de espera',
    status: 'Estado',
    available: 'Disponible',
    unavailable: 'No disponible',
  },
  documents: {
    title: 'Documentos',
    upload: 'Subir documento',
    download: 'Descargar',
    verified: 'Verificado',
    pendingVerification: 'Verificación pendiente',
    type: 'Tipo de documento',
    uploadedAt: 'Subido',
  },
  calendar: {
    title: 'Calendario',
    today: 'Hoy',
    month: 'Mes',
    week: 'Semana',
    day: 'Día',
    newEvent: 'Nuevo evento',
  },
  admin: {
    title: 'Panel de administración',
    users: 'Gestión de usuarios',
    createUser: 'Crear usuario',
    userRole: 'Rol',
    roles: {
      admin: 'Administrador',
      caseManager: 'Gestor de casos',
      staff: 'Personal',
      volunteer: 'Voluntario',
      client: 'Cliente',
    },
    activeUsers: 'Usuarios activos',
    deactivate: 'Desactivar',
    activate: 'Activar',
  },
  profile: {
    title: 'Configuración del perfil',
    personalInfo: 'Información personal',
    changePassword: 'Cambiar contraseña',
    notifications: 'Configuración de notificaciones',
    currentPassword: 'Contraseña actual',
    newPassword: 'Nueva contraseña',
    confirmNewPassword: 'Confirmar nueva contraseña',
  },
  clientPortal: {
    title: 'Auto-registro de clientes',
    welcome: 'Bienvenido a ClientHub',
    description: 'Complete este formulario para registrarse para los servicios. Su información se mantendrá confidencial.',
    step1Title: 'Crear cuenta',
    step2Title: 'Su dirección',
    step3Title: 'Acuerdo de servicio',
    step4Title: 'Firmar y enviar',
    agreementText: 'Acepto los términos y condiciones y autorizo la recopilación de mi información con fines de servicio.',
    signatureLabel: 'Por favor firme abajo',
    clearSignature: 'Borrar firma',
    submitApplication: 'Enviar solicitud',
  },
};

// Chinese translations
const zh: Translations = {
  common: {
    save: '保存',
    cancel: '取消',
    submit: '提交',
    next: '下一步',
    previous: '上一步',
    back: '返回',
    loading: '加载中...',
    error: '错误',
    success: '成功',
    required: '必填',
    optional: '可选',
    search: '搜索',
    filter: '筛选',
    all: '全部',
    yes: '是',
    no: '否',
    edit: '编辑',
    delete: '删除',
    archive: '存档',
    view: '查看',
    create: '创建',
    add: '添加',
    remove: '移除',
    close: '关闭',
    confirm: '确认',
    refresh: '刷新',
    logout: '退出登录',
    login: '登录',
  },
  auth: {
    email: '电子邮件',
    password: '密码',
    confirmPassword: '确认密码',
    forgotPassword: '忘记密码？',
    signIn: '登录',
    signUp: '注册',
    signOut: '退出登录',
    welcomeBack: '欢迎回来',
    enterCredentials: '输入您的电子邮件和密码访问您的账户',
    noAccount: '没有账户？',
    hasAccount: '已有账户？',
    clientPortal: '客户自助注册',
    staffLogin: '员工登录',
  },
  dashboard: {
    title: '控制面板',
    welcome: '欢迎',
    totalClients: '客户总数',
    activeClients: '活跃客户',
    pendingTasks: '待处理任务',
    openTasks: '开放任务',
    upcomingDeadlines: '即将到期',
    recentActivity: '最近活动',
    quickActions: '快速操作',
    newIntake: '新建接收',
    viewClients: '查看客户',
    viewTasks: '查看任务',
    viewCalendar: '查看日历',
  },
  clients: {
    title: '客户',
    newClient: '新客户',
    clientDetails: '客户详情',
    firstName: '名',
    lastName: '姓',
    preferredName: '首选名称',
    dateOfBirth: '出生日期',
    phone: '电话',
    email: '电子邮件',
    address: '地址',
    streetAddress: '街道地址',
    city: '城市',
    state: '州',
    zipCode: '邮编',
    status: '状态',
    active: '活跃',
    inactive: '不活跃',
    pending: '待处理',
    archived: '已存档',
    copyPhone: '复制电话号码',
    copyEmail: '复制电子邮件',
    copied: '已复制！',
  },
  intake: {
    title: '客户接收',
    step1: '参与者详情',
    step2: '紧急联系人',
    step3: '案例管理',
    step4: '人口统计',
    step5: '家庭成员',
    personalInfo: '个人信息',
    contactInfo: '联系信息',
    addressInfo: '地址信息',
    emergencyContact: '紧急联系人',
    caseInfo: '案例信息',
    demographics: '人口统计',
    household: '家庭成员',
  },
  tasks: {
    title: '任务',
    newTask: '新任务',
    taskTitle: '任务标题',
    description: '描述',
    dueDate: '截止日期',
    priority: '优先级',
    high: '高',
    medium: '中',
    low: '低',
    status: '状态',
    pending: '待处理',
    inProgress: '进行中',
    completed: '已完成',
    assignedTo: '分配给',
    claimTask: '认领任务',
    openToClaim: '可认领',
    unassigned: '未分配',
  },
  alerts: {
    title: '警报和通知',
    markAsRead: '标记为已读',
    markAllRead: '全部标记为已读',
    archive: '存档',
    priority: '优先级',
    critical: '紧急',
    high: '高',
    medium: '中',
    low: '低',
    unread: '未读',
  },
  housing: {
    title: '住房',
    programs: '项目',
    applications: '申请',
    waitlist: '等待名单',
    status: '状态',
    available: '可用',
    unavailable: '不可用',
  },
  documents: {
    title: '文档',
    upload: '上传文档',
    download: '下载',
    verified: '已验证',
    pendingVerification: '待验证',
    type: '文档类型',
    uploadedAt: '上传于',
  },
  calendar: {
    title: '日历',
    today: '今天',
    month: '月',
    week: '周',
    day: '日',
    newEvent: '新事件',
  },
  admin: {
    title: '管理面板',
    users: '用户管理',
    createUser: '创建用户',
    userRole: '角色',
    roles: {
      admin: '管理员',
      caseManager: '案例经理',
      staff: '员工',
      volunteer: '志愿者',
      client: '客户',
    },
    activeUsers: '活跃用户',
    deactivate: '停用',
    activate: '激活',
  },
  profile: {
    title: '个人设置',
    personalInfo: '个人信息',
    changePassword: '修改密码',
    notifications: '通知设置',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmNewPassword: '确认新密码',
  },
  clientPortal: {
    title: '客户自助注册',
    welcome: '欢迎来到 ClientHub',
    description: '填写此表格以注册服务。您的信息将被保密。',
    step1Title: '创建账户',
    step2Title: '您的地址',
    step3Title: '服务协议',
    step4Title: '签名并提交',
    agreementText: '我同意条款和条件，并授权收集我的信息用于服务目的。',
    signatureLabel: '请在下方签名',
    clearSignature: '清除签名',
    submitApplication: '提交申请',
  },
};

// Vietnamese translations
const vi: Translations = {
  common: {
    save: 'Lưu',
    cancel: 'Hủy',
    submit: 'Gửi',
    next: 'Tiếp theo',
    previous: 'Trước',
    back: 'Quay lại',
    loading: 'Đang tải...',
    error: 'Lỗi',
    success: 'Thành công',
    required: 'Bắt buộc',
    optional: 'Tùy chọn',
    search: 'Tìm kiếm',
    filter: 'Lọc',
    all: 'Tất cả',
    yes: 'Có',
    no: 'Không',
    edit: 'Sửa',
    delete: 'Xóa',
    archive: 'Lưu trữ',
    view: 'Xem',
    create: 'Tạo',
    add: 'Thêm',
    remove: 'Xóa',
    close: 'Đóng',
    confirm: 'Xác nhận',
    refresh: 'Làm mới',
    logout: 'Đăng xuất',
    login: 'Đăng nhập',
  },
  auth: {
    email: 'Email',
    password: 'Mật khẩu',
    confirmPassword: 'Xác nhận mật khẩu',
    forgotPassword: 'Quên mật khẩu?',
    signIn: 'Đăng nhập',
    signUp: 'Đăng ký',
    signOut: 'Đăng xuất',
    welcomeBack: 'Chào mừng trở lại',
    enterCredentials: 'Nhập email và mật khẩu để truy cập tài khoản',
    noAccount: 'Chưa có tài khoản?',
    hasAccount: 'Đã có tài khoản?',
    clientPortal: 'Đăng ký khách hàng',
    staffLogin: 'Đăng nhập nhân viên',
  },
  dashboard: {
    title: 'Bảng điều khiển',
    welcome: 'Chào mừng',
    totalClients: 'Tổng khách hàng',
    activeClients: 'Khách hàng hoạt động',
    pendingTasks: 'Công việc chờ xử lý',
    openTasks: 'Công việc mở',
    upcomingDeadlines: 'Hạn sắp tới',
    recentActivity: 'Hoạt động gần đây',
    quickActions: 'Thao tác nhanh',
    newIntake: 'Tiếp nhận mới',
    viewClients: 'Xem khách hàng',
    viewTasks: 'Xem công việc',
    viewCalendar: 'Xem lịch',
  },
  clients: {
    title: 'Khách hàng',
    newClient: 'Khách hàng mới',
    clientDetails: 'Chi tiết khách hàng',
    firstName: 'Tên',
    lastName: 'Họ',
    preferredName: 'Tên ưa thích',
    dateOfBirth: 'Ngày sinh',
    phone: 'Điện thoại',
    email: 'Email',
    address: 'Địa chỉ',
    streetAddress: 'Địa chỉ đường',
    city: 'Thành phố',
    state: 'Tiểu bang',
    zipCode: 'Mã bưu chính',
    status: 'Trạng thái',
    active: 'Hoạt động',
    inactive: 'Không hoạt động',
    pending: 'Chờ xử lý',
    archived: 'Đã lưu trữ',
    copyPhone: 'Sao chép số điện thoại',
    copyEmail: 'Sao chép email',
    copied: 'Đã sao chép!',
  },
  intake: {
    title: 'Tiếp nhận khách hàng',
    step1: 'Thông tin người tham gia',
    step2: 'Liên hệ khẩn cấp',
    step3: 'Quản lý hồ sơ',
    step4: 'Nhân khẩu học',
    step5: 'Hộ gia đình',
    personalInfo: 'Thông tin cá nhân',
    contactInfo: 'Thông tin liên hệ',
    addressInfo: 'Thông tin địa chỉ',
    emergencyContact: 'Liên hệ khẩn cấp',
    caseInfo: 'Thông tin hồ sơ',
    demographics: 'Nhân khẩu học',
    household: 'Thành viên hộ gia đình',
  },
  tasks: {
    title: 'Công việc',
    newTask: 'Công việc mới',
    taskTitle: 'Tiêu đề công việc',
    description: 'Mô tả',
    dueDate: 'Hạn chót',
    priority: 'Ưu tiên',
    high: 'Cao',
    medium: 'Trung bình',
    low: 'Thấp',
    status: 'Trạng thái',
    pending: 'Chờ xử lý',
    inProgress: 'Đang thực hiện',
    completed: 'Hoàn thành',
    assignedTo: 'Phân công cho',
    claimTask: 'Nhận công việc',
    openToClaim: 'Có thể nhận',
    unassigned: 'Chưa phân công',
  },
  alerts: {
    title: 'Cảnh báo và Thông báo',
    markAsRead: 'Đánh dấu đã đọc',
    markAllRead: 'Đánh dấu tất cả đã đọc',
    archive: 'Lưu trữ',
    priority: 'Ưu tiên',
    critical: 'Khẩn cấp',
    high: 'Cao',
    medium: 'Trung bình',
    low: 'Thấp',
    unread: 'Chưa đọc',
  },
  housing: {
    title: 'Nhà ở',
    programs: 'Chương trình',
    applications: 'Đơn đăng ký',
    waitlist: 'Danh sách chờ',
    status: 'Trạng thái',
    available: 'Có sẵn',
    unavailable: 'Không có sẵn',
  },
  documents: {
    title: 'Tài liệu',
    upload: 'Tải lên tài liệu',
    download: 'Tải xuống',
    verified: 'Đã xác minh',
    pendingVerification: 'Chờ xác minh',
    type: 'Loại tài liệu',
    uploadedAt: 'Đã tải lên',
  },
  calendar: {
    title: 'Lịch',
    today: 'Hôm nay',
    month: 'Tháng',
    week: 'Tuần',
    day: 'Ngày',
    newEvent: 'Sự kiện mới',
  },
  admin: {
    title: 'Bảng quản trị',
    users: 'Quản lý người dùng',
    createUser: 'Tạo người dùng',
    userRole: 'Vai trò',
    roles: {
      admin: 'Quản trị viên',
      caseManager: 'Quản lý hồ sơ',
      staff: 'Nhân viên',
      volunteer: 'Tình nguyện viên',
      client: 'Khách hàng',
    },
    activeUsers: 'Người dùng hoạt động',
    deactivate: 'Vô hiệu hóa',
    activate: 'Kích hoạt',
  },
  profile: {
    title: 'Cài đặt hồ sơ',
    personalInfo: 'Thông tin cá nhân',
    changePassword: 'Đổi mật khẩu',
    notifications: 'Cài đặt thông báo',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmNewPassword: 'Xác nhận mật khẩu mới',
  },
  clientPortal: {
    title: 'Đăng ký khách hàng',
    welcome: 'Chào mừng đến ClientHub',
    description: 'Hoàn thành biểu mẫu này để đăng ký dịch vụ. Thông tin của bạn sẽ được bảo mật.',
    step1Title: 'Tạo tài khoản',
    step2Title: 'Địa chỉ của bạn',
    step3Title: 'Thỏa thuận dịch vụ',
    step4Title: 'Ký và Gửi',
    agreementText: 'Tôi đồng ý với các điều khoản và điều kiện và cho phép thu thập thông tin của tôi cho mục đích dịch vụ.',
    signatureLabel: 'Vui lòng ký bên dưới',
    clearSignature: 'Xóa chữ ký',
    submitApplication: 'Gửi đơn đăng ký',
  },
};

const translations: Record<Language, Translations> = { en, es, zh, vi };

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    const savedLang = localStorage.getItem('preferred-language') as Language;
    if (savedLang && availableLanguages.some(l => l.code === savedLang)) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferred-language', lang);
    // Update document lang attribute
    document.documentElement.lang = lang;
  };

  const t = (key: string, replacements?: Record<string, string>): string => {
    const keys = key.split('.');
    let value: string | Translations = translations[language];

    for (const k of keys) {
      if (typeof value === 'object' && value !== null && k in value) {
        value = value[k];
      } else {
        // Fall back to English if key not found
        value = translations.en;
        for (const fallbackKey of keys) {
          if (typeof value === 'object' && value !== null && fallbackKey in value) {
            value = value[fallbackKey];
          } else {
            return key; // Return the key if not found in any language
          }
        }
        break;
      }
    }

    let result = typeof value === 'string' ? value : key;

    // Handle replacements like {name}
    if (replacements) {
      Object.entries(replacements).forEach(([placeholder, replacement]) => {
        result = result.replace(new RegExp(`\\{${placeholder}\\}`, 'g'), replacement);
      });
    }

    return result;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
